export const frontPackage = [
    { key: 0, label: "react-props", color:"info" },
    { key: 1, label: "react-props", color:"warning" },
    { key: 2, label: "prop-types", color:"success" },
    { key: 3, label: "react-router-dom@6.3.0", color:"secondary" },
    { key: 4, label: "json-server", color:"primary" },
    { key: 5, label: "axios", color:"error" },
    { key: 6, label: "lodash"  , color:"info" },
    { key: 7, label: "yup"  , color:"warning"},
    { key: 8, label: "formik"  , color:"success" },
    { key: 9, label: "react-toastify"  , color:"secondary" },
    { key: 10, label: "react-hot-toast"  , color:"primary" },
    { key: 11, label: "immerjs"  , color:"error" },
    { key: 12, label: "react-swipeable-views"  , color:"warning" },
    { key: 13, label: "react-typed"  , color:"success"},
    { key: 14, label: "particles"  , color:"secondary"},
    { key: 15, label: "react-text-transition"  , color:"primary" },
    { key: 16, label: "react-random-reveal"  , color:"error" },
    { key: 17, label: "react-helmet"  , color:"info" },
    { key: 19, label: "react-counter"  , color:"warning"},
    { key: 20, label: "react-slick"  , color:"success"},
    { key: 21, label: "google-recaptcha"  , color:"secondary" },
    { key: 22, label: "react-number-format"  , color:"primary" },
    { key: 23, label: "react-ellipsis-text"  , color:"warning" },
]

export const backEndPackage = [
    { key: 0, label: "express", color:"error" },
    { key: 1, label: "lodash", color:"info" },
    { key: 6, label: "joi", color:"warning" },
    { key: 2, label: "jsonwebtoken", color:"success" },
    { key: 5, label: "axios", color:"primary" },
    { key: 3, label: "express-async-error", color:"warning" },
    { key: 4, label: "winston", color:"secondary" },
    { key: 7, label: "formik", color:"error" },
    { key: 8, label: "yup", color:"warning" },
    { key: 10, label: "kavenegar", color:"success" },
    { key: 11, label: "zarinpal", color:"secondary" },
    { key: 12, label: "config", color:"primary" },
    { key: 13, label: "bcrypt", color:"warning" },
]